# Project information
site_name: 'Кодирование автомобилей VAG'
site_description: 'Основные настройки различных палтформ концерна VAG'
site_author: 'Andrey Topchiy'
site_url: 'http://www.vwcoding.ru/'

# Repository
repo_name: 'Kanaduchi/mqb'
repo_url: 'https://github.com/Kanaduchi/mqb'
edit_uri: 'https://github.com/Kanaduchi/mqb/edit/1com/docs/'

# Copyright
copyright: 'Copyright &copy; 2020 - Andrey Topchiy'

nav:
  - Главная страница: index.md
  - Платформа PQ26: PQ26/main.md
  - Платформа PQ26:
    - Общая информация: PQ26/main.md
    - Освещение:
      - Управление освещением: PQ26/lights.md
      - Нестандартные световые решения: PQ26/extraLights.md
      - Обозначения ламп: PQ26/codingLights.md
      - Обозначения ламп c картинками: PQ26/codingLightsPictures.md
      - Установка светодиодов: PQ26/setLED.md
    - Стеклоочистители / Датчик дождя и света: PQ26/wash.md
    - Климат / Обогрев зеркал и стекол: PQ26/climate.md
    - Двери, стекла, цз, брелок и штатная сигнализация: PQ26/security.md
    - Панель приборов:
      - Общие кодировки: PQ26/instrPanel.md
      - Кривые подсветки панели приборов: PQ26/instrPanelCoding.md
    - Тормоза и шины: PQ26/brakes.md
    - Динамика и управление: PQ26/drive.md
    - Мультимедиа: PQ26/multimedia.md
    - Дооснащение: PQ26/addons.md
    - Словарь немецких терминов: PQ26/german.md
  - Платформа MQB: MQB/main.md
  - Платформа MQB:
    - Общая информация: MQB/main.md
    - Ассистенты водителя: MQB/assistents.md
    - Системы активной безопасности: MQB/active_systems.md
    - Движение и управление: MQB/drive.md
    - Парковка и маневрирование: MQB/parking.md
    - Эстетическая подсветка:
      - Общие настройки: MQB/esteticLights.md
      - Кодирование: MQB/esteticLightsCoding.md
    - Зеркала и стеклоочистители: MQB/wash.md
    - Отпирание и запирание: MQB/security.md
    - Освещение:
      - Кодирование фонарей: MQB/codingLights.md
      - Передние фонари:  MQB/headLights.md
      - Задние фонари: MQB/rearLights.md
    - Звук: MQB/sound.md
    - Климат: MQB/climate.md
    - Приборная панель: MQB/AID.md
    - Головное устройство: MQB/headDevice.md
    - Шины: MQB/tires.md
    - Дооснащение: MQB/addons.md
  - Инструкция ODIS E: odis-e.md
  - Кодирование байтов и битов: bytes.md
  - История изменений: history.md
  - Поддержать проект: https://money.yandex.ru/to/4100110582992748/50

theme:
  name: null
  favicon: 'vw.png'
  custom_dir: 'material'
  highlightjs: false
  language: ru
  palette:
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'vw.png'
  feature:
    tabs: true
  # 404 page
  static_templates:
    - 404.html

extra_css:
  - 'custom.css'

extra:
  search:
    language: 'en, ru'

markdown_extensions:
  - meta
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
