# Project information
site_name: 'Кодирование MQB платформы'
site_description: 'Основные настройки MQB платформы'
site_author: 'Andrey Topchiy'

# Repository
repo_name: 'Kanaduchi/mqb'
repo_url: 'https://github.com/Kanaduchi/mqb'

# Copyright
copyright: 'Copyright &copy; 2020 - Andrey Topchiy'

nav:
  - Безопасность: security.md
  - Освещение: lights.md
  - Комфорт: comfort.md
  - Климат: climate.md
  - Омыватель фар: wash.md
  - Звук: sound.md
  - Движение и ассистенты: drive.md
  - Ассистенты: assistents.md
  - Шины: tires.md

theme:
  name: null
  custom_dir: 'material'
  highlightjs: false
  language: ru
  palette:
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: "\uE80C"
  feature:
    tabs: true