site_name: Кодирование MQB платформы
nav:
    - Безопасность: security.md
    - Освещение: lights.md
    - Комфорт: comfort.md
    - Климат: climate.md
    - Звук: sound.md
    - Движение и ассистенты: drive.md
theme:
  name: mkdocs
  highlightjs: false