# Project information
site_name: Кодирование автомобилей VAG
site_description: Основные настройки различных платформ концерна VAG
site_author: Andrey Topchiy
site_url: http://www.vwcoding.ru

# Hot news
hot_news_date: 16.06.2020
hot_news: >
  1. Теперь страницы сайта можно экспортировать офлайн в PDF формат. <br>
  Для этого в правом верхнем углу страницы появился значок <svg style="width:32px;height:32px" viewBox="0 0 24 24"><path fill="currentColor" d="M17,13L12,18L7,13H10V9H14V13M19.35,10.03C18.67,6.59 15.64,4 12,4C9.11,4 6.6,5.64 5.35,8.03C2.34,8.36 0,10.9 0,14A6,6 0 0,0 6,20H19A5,5 0 0,0 24,15C24,12.36 21.95,10.22 19.35,10.03Z"></path></svg><br>
  2. Добавлен новый раздел с кодировками платформы MLB-Evo <br>
  2. Добавлена инструкция по установке и кодированию автоматического переключателя света

# Repository
repo_name: Kanaduchi/mqb
repo_url: https://github.com/Kanaduchi/mqb
edit_uri: https://github.com/Kanaduchi/mqb/edit/1com/docs/

# Copyright
copyright: Copyright &copy; 2020 - Andrey Topchiy

# Main directory
docs_dir: docs/

nav:
  - Главная страница: index.md
  - Платформа MQB: MQB/main.md
  - Платформа MQB:
      - Общая информация: MQB/main.md
      - Ассистенты водителя: MQB/assistents.md
      - Системы активной безопасности: MQB/active_systems.md
      - Движение и управление: MQB/drive.md
      - Парковка и маневрирование: MQB/parking.md
      - Эстетическая подсветка:
          - Общие настройки: MQB/esteticLights.md
          - Кодирование: MQB/esteticLightsCoding.md
      - Зеркала и стеклоочистители: MQB/wash.md
      - Отпирание и запирание: MQB/security.md
      - Освещение:
          - Кодирование фонарей: MQB/codingLights.md
          - Передние фонари:  MQB/headLights.md
          - Задние фонари: MQB/rearLights.md
      - Звук: MQB/sound.md
      - Климат: MQB/climate.md
      - Приборная панель: MQB/AID.md
      - Головное устройство: MQB/headDevice.md
      - Шины:
          - Общие кодировки: MQB/tires.md
          - Генератор параметрии: MQB/tiresCoding.md
      - Дооснащение: MQB/addons.md
  - Платформа MLB-Evo: MLB-Evo/main.md
  - Платформа MLB-Evo:
      - Общая информация: MLB-Evo/main.md
      - Ассистенты водителя: MLB-Evo/assistents.md
      - Безопасность. Отпирание и запирание: MLB-Evo/security.md
      - Комфорт: MLB-Evo/comfort.md
      - Освещение: MLB-Evo/lights.md
      - Приборная панель: MLB-Evo/AID.md
      - Головное устройство: MLB-Evo/headDevice.md
  - Платформа PQ26: PQ26/main.md
  - Платформа PQ26:
      - Общая информация: PQ26/main.md
      - Освещение:
          - Управление освещением: PQ26/lights.md
          - Нестандартные световые решения: PQ26/extraLights.md
          - Обозначения ламп: PQ26/codingLights.md
          - Обозначения ламп c картинками: PQ26/codingLightsPictures.md
          - Установка светодиодов: PQ26/setLED.md
      - Стеклоочистители / Датчик дождя и света: PQ26/wash.md
      - Климат / Обогрев зеркал и стекол: PQ26/climate.md
      - Двери, стекла, цз, брелок и штатная сигнализация: PQ26/security.md
      - Панель приборов:
          - Общие кодировки: PQ26/instrPanel.md
          - Кривые подсветки панели приборов: PQ26/instrPanelCoding.md
      - Тормоза и шины: PQ26/brakes.md
      - Динамика и управление: PQ26/drive.md
      - Мультимедиа: PQ26/multimedia.md
      - Дооснащение: PQ26/addons.md
      - Словарь немецких терминов: PQ26/german.md
  - Платформа PQ35: PQ35/main.md
  - Платформа PQ35:
      - Общая информация: PQ35/main.md
      - Управление и динамика: PQ35/drive.md
      - Свет: PQ35/lights.md
      - Мультимедиа: PQ35/multimedia.md
      - Комфорт: PQ35/comfort.md
      - Прочие функции: PQ35/other.md
      - Кодировки Tiguan 1st Gen:
          - Управление и динамика: PQ35/Tiguan/drive.md
          - Комфорт: PQ35/Tiguan/comfort.md
          - Свет: PQ35/Tiguan/lights.md
          - Приборная панель: PQ35/Tiguan/instrPanel.md
          - Мультимедиа: PQ35/Tiguan/multimedia.md
  - Инструкция ODIS E: odis-e.md
  - Кодирование байтов и битов: bytes.md
  - История изменений: history.md
  - Обратная связь: questions.md
  - Поддержать проект: https://money.yandex.ru/to/4100110582992748/50

theme:
  name: material
  custom_dir: overrides
  favicon: assets/logo.png
  palette:
    scheme: preference
  highlightjs: false
  language: ru
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  features:
    - tabs
    #- instant
  # 404 page
  static_templates:
    - 404.html

extra_css:
  - assets/custom.css

plugins:
  - search:
      lang:
        - en
        - de
        - ru
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT

markdown_extensions:
  - meta
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
