site_name: Кодирование MQB платформы
nav:
  - Безопасность: security.md
  - Освещение: lights.md
  - Комфорт: comfort.md
  - Климат: climate.md
  - Омыватель фар: wash.md
  - Звук: sound.md
  - Движение и ассистенты: drive.md
  - Ассистенты: assistents.md
  - Шины: tires.md

theme:
  custom_dir: 'material'
  highlightjs: false
