site_name: Кодирование MQB платформы
nav:
  - Безопасность: security.md
  - Освещение: lights.md
  - Комфорт: comfort.md
  - Климат: climate.md
  - Омыватель фар: wash.md
  - Звук: sound.md
  - Движение и ассистенты: drive.md
  - Ассистенты: assistents.md
  - Шины: tires.md

theme:
  name: null
  custom_dir: 'material'
  highlightjs: false
  language: en
  palette:
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: "\uE80C"
  feature:
    tabs: true
