# Project information
site_name: 'Кодирование MQB платформы'
site_description: 'Основные настройки MQB платформы'
site_author: 'Andrey Topchiy'

# Repository
repo_name: 'Kanaduchi/mqb'
repo_url: 'https://github.com/Kanaduchi/mqb'
edit_uri: 'https://github.com/Kanaduchi/mqb/edit/1com/docs/'

# Copyright
copyright: 'Copyright &copy; 2020 - Andrey Topchiy'

extra_css:
  - 'css/app.css'
extra_javascript:
  - 'js/script.js'

nav:
  - Безопасность: security.md
  - Освещение: lights.md
  - Комфорт: comfort.md
  - Климат: climate.md
  - Омыватель фар: wash.md
  - Звук: sound.md
  - Движение: drive.md
  - Ассистенты: assistents.md
  - Шины: tires.md
  - ODIS E: odis-e.md

theme:
  name: null
  custom_dir: 'material'
  highlightjs: false
  language: ru
  palette:
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'vw.svg'
  feature:
    tabs: true
  # 404 page
  static_templates:
    - 404.html

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true